### ISSUE TITLE
Memory problem while training process

### ISSUE THREAD

**Issue by DaddyWesker** [SinghJasdeep/Attention-on-Attention-for-VQA#3]
Hello. Launching main.py and recieveing memory error (cannot allocate memory) on the very first epoch. Launching on PC with 64 gb ram, 1080ti and core i9. Does this model requires more than 64 gb? Thanks in advance for your reply.

**Comment by DaddyWesker** [comment]
Here is what lies in git bash window. Forgot to say that i'm running on ubuntu system.
"(py2.7) daddywesker@k4:~/Experiments/Attention-on-attention$ python main.py
loading dictionary from data/dictionary.pkl
loading features from h5 file
/home/daddywesker/.conda/envs/py2.7/lib/python2.7/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
v_dim: 2048     q_dim: 1280     num_hid: 1280    num ans candidates: 3129
main.py:54: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data, a=0.01)
loading features from h5 file
/home/daddywesker/Experiments/Attention-on-attention/train.py:57: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(model.parameters(), 0.25)
/home/daddywesker/Experiments/Attention-on-attention/train.py:62: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  total_loss += loss.data[0] * v.size(0)
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    train(model, train_loader, eval_loader, args.epochs, output, args.optimizer, args.weight_decay)
  File "/home/daddywesker/Experiments/Attention-on-attention/train.py", line 69, in train
    eval_score, bound, V_loss = evaluate(model, eval_loader)
  File "/home/daddywesker/Experiments/Attention-on-attention/train.py", line 87, in evaluate
    for v, b, q, a in iter(dataloader):
  File "/home/daddywesker/.conda/envs/py2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/daddywesker/.conda/envs/py2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 239, in __init__
    w.start()
  File "/home/daddywesker/.conda/envs/py2.7/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/home/daddywesker/.conda/envs/py2.7/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory"

**Comment by ZhuFengdaaa** [comment]
https://github.com/hengyuan-hu/bottom-up-attention-vqa/issues/23

**Comment by DaddyWesker** [comment]
@ZhuFengdaaa Well, i've raised virtual memory to 100 gb now it launches but 11 hrs on 1 epoch is kinda long. For some reason, code doesn't use gpu at all capacity (launched on g1)
![screenshot from 2018-07-02 15-22-49](https://user-images.githubusercontent.com/10774222/42163587-e28e7622-7e0b-11e8-97c2-e011b30e80f3.png)

**Comment by ZhuFengdaaa** [comment]
You can check if disk I/O is the bottleneck. If you load all data into physical memory, training process can be very fast. I have 64GB physical memory, by the way.

**Comment by DaddyWesker** [comment]
Thanks for helping. Everything is fine right now
